import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { AdminService, CommunityForm, MassForm, ParishForm } from './core/services/admin.service';

const mass = (): MassForm => ({ day: 'Sunday', time: '' });
const community = (): CommunityForm => ({ name: '', address: '', phone: '', imageUrl: '', massSchedules: [mass()] });
const blank = (): ParishForm => ({ name: '', sector: '', city: '', state: 'MG', address: '', phone: '', imageUrl: '', isPremium: false, massSchedules: [mass()], communities: [] });
const days = [
  { value: 'Monday', label: 'Segunda-feira' }, { value: 'Tuesday', label: 'Terça-feira' },
  { value: 'Wednesday', label: 'Quarta-feira' }, { value: 'Thursday', label: 'Quinta-feira' },
  { value: 'Friday', label: 'Sexta-feira' }, { value: 'Saturday', label: 'Sábado' },
  { value: 'Sunday', label: 'Domingo' }
];

@Component({
  selector: 'app-root', standalone: true, imports: [CommonModule, FormsModule],
  styles: [`:host{display:block;min-height:100vh;background:#f5f7f4;color:#123f36;font-family:Arial}header{background:#0b4039;color:#fff;padding:22px 7%;display:flex;justify-content:space-between}header a{color:#fff}.wrap{max-width:1180px;margin:auto;padding:30px 20px}.login,.box{background:#fff;border-radius:14px;padding:25px;box-shadow:0 8px 22px #123f3615}.login{max-width:420px;margin:70px auto}.grid{display:grid;grid-template-columns:1.4fr .8fr;gap:24px}.fields{display:grid;grid-template-columns:1fr 1fr;gap:13px}label{font-size:13px;font-weight:bold;display:block}input,select{width:100%;box-sizing:border-box;padding:10px;margin-top:5px;border:1px solid #cad9cf;border-radius:7px;background:#fff;color:#123f36}.plan{display:flex;align-items:center;gap:9px;margin-top:18px;padding:12px;border-radius:8px;background:#fff7e7;color:#765216}.plan input{width:auto;margin:0}.section{margin-top:25px;border-top:1px solid #e2e9e3;padding-top:18px}.mass{display:grid;grid-template-columns:1fr 1fr auto;gap:8px;margin:8px 0}.community{padding:16px;margin:14px 0;border:1px solid #dbe7dd;border-radius:10px;background:#f8faf8}button{border:0;border-radius:7px;padding:9px 13px;font-weight:bold;cursor:pointer}.primary{background:#dfa93d}.link{background:none;color:#21644f;padding-left:0}.danger{color:#a93728}.item{padding:13px 0;border-bottom:1px solid #e2e9e3}.status{color:#a93728}.upload{display:flex;gap:8px;align-items:end;margin-top:5px}.upload input{padding:7px;flex:1}.upload button{white-space:nowrap}.preview{display:block;width:100%;height:125px;object-fit:cover;border-radius:7px;margin-top:8px;border:1px solid #dbe7dd}.hint{color:#687b71;font-size:12px;margin:7px 0 0}@media(max-width:800px){.grid,.fields{grid-template-columns:1fr}.upload{display:block}.upload button{margin-top:8px}}`],
  template: `<header><b>Igreja Conecta · Administração</b><a href="/">Portal público</a></header><main class="wrap">
  <section class="login" *ngIf="!open"><h1>Acesso ADM</h1><input type="password" [(ngModel)]="key" placeholder="Chave"><p><button class="primary" (click)="unlock()">Entrar</button></p><p class="status">{{message}}</p></section>
  <div class="grid" *ngIf="open"><section class="box"><h1>{{form.id?'Editar paróquia':'Nova paróquia'}}</h1><div class="fields">
  <label>Nome<input [(ngModel)]="form.name"></label><label>Setor<input [(ngModel)]="form.sector"></label><label>Cidade<input [(ngModel)]="form.city"></label><label>Endereço da matriz<input [(ngModel)]="form.address"></label><label>Telefone<input [(ngModel)]="form.phone"></label>
  <label>Foto da matriz<input [(ngModel)]="form.imageUrl" placeholder="Envie abaixo ou informe uma URL"></label></div><label class="plan"><input type="checkbox" [(ngModel)]="form.isPremium"> Paróquia PLUS — habilitar página completa</label>
  <div class="upload"><input type="file" accept="image/jpeg,image/png,image/webp" (change)="uploadMatrix($event)"><button class="primary" [disabled]="uploadingMatrix" (click)="uploadMatrix()">{{uploadingMatrix?'Enviando...':'Enviar foto da matriz'}}</button></div><p class="hint">JPG, PNG ou WEBP, até 5 MB.</p><img *ngIf="form.imageUrl" class="preview" [src]="form.imageUrl" alt="Prévia da matriz">
  <div class="section"><h2>Horários da matriz</h2><div class="mass" *ngFor="let m of form.massSchedules;let i=index"><select [(ngModel)]="m.day"><option *ngFor="let day of days" [value]="day.value">{{day.label}}</option></select><input [(ngModel)]="m.time" inputmode="numeric" maxlength="5" placeholder="09:30" (blur)="formatTime(m)"><button class="link danger" (click)="form.massSchedules.splice(i,1)">Remover</button></div><button class="link" (click)="form.massSchedules.push(newMass())">+ Adicionar horário da matriz</button></div>
  <div class="section"><h2>Comunidades vinculadas</h2><div class="community" *ngFor="let c of form.communities;let i=index"><h3>Comunidade {{i+1}}</h3><div class="fields"><label>Nome<input [(ngModel)]="c.name"></label><label>Endereço<input [(ngModel)]="c.address"></label><label>Telefone<input [(ngModel)]="c.phone"></label><label>Foto<input [(ngModel)]="c.imageUrl" placeholder="Envie abaixo ou informe uma URL"></label></div><div class="upload"><input type="file" accept="image/jpeg,image/png,image/webp" (change)="uploadCommunity($event, i)"><button class="primary" [disabled]="uploadingCommunity===i" (click)="uploadCommunity(undefined, i)">{{uploadingCommunity===i?'Enviando...':'Enviar foto'}}</button></div><img *ngIf="c.imageUrl" class="preview" [src]="c.imageUrl" alt="Prévia da comunidade"><b>Horários da comunidade</b><div class="mass" *ngFor="let m of c.massSchedules;let j=index"><select [(ngModel)]="m.day"><option *ngFor="let day of days" [value]="day.value">{{day.label}}</option></select><input [(ngModel)]="m.time" inputmode="numeric" maxlength="5" placeholder="09:30" (blur)="formatTime(m)"><button class="link danger" (click)="c.massSchedules.splice(j,1)">Remover</button></div><button class="link" (click)="c.massSchedules.push(newMass())">+ horário</button><button class="link danger" (click)="form.communities?.splice(i,1)">Excluir comunidade</button></div><button class="link" (click)="addCommunity()">+ Adicionar comunidade</button></div>
  <p><button class="primary" (click)="save()">Salvar paróquia</button> <button class="link" (click)="reset()">Nova paróquia</button></p><p class="status">{{message}}</p></section><section class="box"><h2>Paróquias cadastradas</h2><div class="item" *ngFor="let p of items"><b>{{p.name}}</b><br>{{p.city}} · {{p.massSchedules.length}} horário(s)<br><button class="link" (click)="edit(p)">Editar</button><button class="link danger" (click)="remove(p)">Excluir</button></div></section></div></main>`
})
export class AdminPageComponent {
  key = ''; open = false; message = ''; form = blank(); items: ParishForm[] = [];
  readonly days = days;
  matrixFile?: File; communityFiles: Record<number, File | undefined> = {}; uploadingMatrix = false; uploadingCommunity?: number;
  constructor(private api: AdminService) {}
  newMass() { return mass(); }
  formatTime(mass: MassForm) { const digits = (mass.time || '').replace(/\D/g, ''); if (!digits) return; const padded = digits.length <= 2 ? `${digits.padStart(2, '0')}00` : digits.padStart(4, '0').slice(-4); const hour = Number(padded.slice(0, 2)); const minute = Number(padded.slice(2)); if (hour <= 23 && minute <= 59) mass.time = `${padded.slice(0, 2)}:${padded.slice(2)}`; }
  unlock() { this.api.list(this.key).subscribe({ next: x => { this.open = true; this.items = x; }, error: () => this.message = 'Chave inválida ou serviço indisponível.' }); }
  edit(p: ParishForm) { this.form = JSON.parse(JSON.stringify(p)); this.form.communities ??= []; this.form.massSchedules ??= []; window.scrollTo({ top: 0, behavior: 'smooth' }); }
  reset() { this.form = blank(); this.matrixFile = undefined; this.communityFiles = {}; }
  addCommunity() { this.form.communities?.push(community()); }
  uploadMatrix(event?: Event) { if (event) this.matrixFile = this.fileFrom(event); if (!this.matrixFile) { this.message = 'Selecione a imagem da matriz antes de enviar.'; return; } this.uploadingMatrix = true; this.upload(this.matrixFile, url => this.form.imageUrl = url, () => this.uploadingMatrix = false); }
  uploadCommunity(event: Event | undefined, index: number) { if (event) this.communityFiles[index] = this.fileFrom(event); const file = this.communityFiles[index]; if (!file) { this.message = 'Selecione a imagem da comunidade antes de enviar.'; return; } this.uploadingCommunity = index; this.upload(file, url => { if (this.form.communities) this.form.communities[index].imageUrl = url; }, () => this.uploadingCommunity = undefined); }
  save() { (this.form.id ? this.api.update(this.key, this.form) : this.api.create(this.key, this.form)).subscribe({ next: () => { this.message = 'Salvo com sucesso.'; this.reset(); this.unlock(); }, error: () => this.message = 'Não foi possível salvar.' }); }
  remove(p: ParishForm) { if (p.id && confirm('Excluir?')) this.api.delete(this.key, p.id).subscribe(() => this.unlock()); }
  private fileFrom(event: Event) { return (event.target as HTMLInputElement).files?.[0]; }
  private upload(file: File, assign: (url: string) => void, complete: () => void) { this.api.uploadImage(this.key, file).subscribe({ next: r => { assign(r.url); this.message = 'Imagem enviada. Clique em Salvar paróquia para vincular a foto.'; complete(); }, error: e => { this.message = e.error?.message ?? 'Não foi possível enviar a imagem.'; complete(); } }); }
}
