import { CommonModule } from '@angular/common';
import { Component, OnInit } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { Parish } from './core/models/parish';
import { ParishService } from './core/services/parish.service';
import { AdminService, ParishForm } from './core/services/admin.service';

@Component({
  selector: 'app-admin', standalone: true, imports: [CommonModule, FormsModule],
  template: `<main class="admin-page"><header class="admin-header"><a href="/">← Voltar ao site</a><div><small>ÁREA RESTRITA</small><h1>Painel da Diocese</h1></div></header><section class="admin-login" *ngIf="!unlocked"><h2>Acesso administrativo</h2><p>Informe a chave definida no Render para cadastrar uma paróquia.</p><input [(ngModel)]="key" type="password" placeholder="Chave de administrador"><button (click)="unlock()">Entrar</button><p class="admin-error" *ngIf="message">{{ message }}</p></section><section class="admin-form-wrap" *ngIf="unlocked"><div><p class="eyebrow dark"><span></span> Novo cadastro</p><h2>Adicionar paróquia</h2><p class="admin-help">A foto é uma URL. Você pode usar uma imagem hospedada no Cloudinary, Google Drive público ou no próprio site da paróquia.</p></div><form class="admin-form" (ngSubmit)="save()"><label>Nome da paróquia<input [(ngModel)]="form.name" name="name" required placeholder="Ex.: Paróquia Nossa Senhora das Dores"></label><div class="form-row"><label>Cidade<input [(ngModel)]="form.city" name="city" required placeholder="Guaxupé"></label><label>Estado<input [(ngModel)]="form.state" name="state" required maxlength="2"></label></div><label>Setor<select [(ngModel)]="form.sector" name="sector" required><option value="">Selecione</option><option *ngFor="let sector of sectors" [value]="sector">{{ sector }}</option></select></label><label>Endereço<input [(ngModel)]="form.address" name="address" placeholder="Rua, número e bairro"></label><div class="form-row"><label>Telefone<input [(ngModel)]="form.phone" name="phone" placeholder="(35) 0000-0000"></label><label>Foto da paróquia (URL)<input [(ngModel)]="form.imageUrl" name="imageUrl" type="url" placeholder="https://..."></label></div><fieldset><legend>Primeiro horário de missa <small>(opcional)</small></legend><div class="form-row three"><label>Dia<select [(ngModel)]="form.massDay" name="massDay"><option *ngFor="let day of days" [value]="day.value">{{ day.label }}</option></select></label><label>Horário<input [(ngModel)]="form.massTime" name="massTime" type="time"></label><label>Detalhe<input [(ngModel)]="form.massDescription" name="massDescription" placeholder="Missa matriz"></label></div></fieldset><label class="check-row"><input [(ngModel)]="form.isPremium" name="isPremium" type="checkbox"> Comunidade parceira</label><button class="save-button" [disabled]="saving">{{ saving ? 'Salvando...' : 'Salvar paróquia' }}</button><p class="admin-message" [class.admin-error]="isError" *ngIf="message">{{ message }}</p></form></section></main>`, styles: []
})
export class AdminComponent {
  key = sessionStorage.getItem('igrejaConectaAdminKey') ?? ''; unlocked = Boolean(this.key); saving = false; message = ''; isError = false;
  readonly sectors = ['Setor Guaxupé', 'Setor Poços de Caldas', 'Setor Passos', 'Setor Cássia']; readonly days = [{ value: 'Sunday', label: 'Domingo' }, { value: 'Saturday', label: 'Sábado' }, { value: 'Monday', label: 'Segunda-feira' }];
  form: ParishForm = { name: '', sector: '', city: '', state: 'MG', address: '', phone: '', imageUrl: '', isPremium: false, massDay: 'Sunday', massTime: '', massDescription: '' };
  constructor(private readonly adminService: AdminService) {}
  unlock() { if (!this.key.trim()) { this.message = 'Informe a chave de administrador.'; return; } sessionStorage.setItem('igrejaConectaAdminKey', this.key.trim()); this.unlocked = true; this.message = ''; }
  save() { this.saving = true; this.message = ''; this.adminService.create(this.key, this.form).subscribe({ next: () => { this.saving = false; this.isError = false; this.message = 'Paróquia cadastrada com sucesso.'; this.form = { name: '', sector: '', city: '', state: 'MG', address: '', phone: '', imageUrl: '', isPremium: false, massDay: 'Sunday', massTime: '', massDescription: '' }; }, error: error => { this.saving = false; this.isError = true; this.message = error.status === 401 ? 'Chave administrativa inválida.' : 'Não foi possível salvar. Confira os campos e tente novamente.'; } }); }
}

@Component({
  selector: 'app-root', standalone: true, imports: [CommonModule, FormsModule, AdminComponent],
  template: `
    <app-admin *ngIf="isAdmin"></app-admin><ng-container *ngIf="!isAdmin"><header class="site-header"><a class="brand" href="#inicio"><span class="brand-mark">✦</span><span><strong>Igreja</strong> Conecta<small>Diocese de Guaxupé</small></span></a><nav><a href="#missas">Missas</a><a href="#paroquias">Paróquias</a><a href="#sobre">Sobre</a></nav><a class="header-action" href="#paroquias">Encontrar igreja <span>→</span></a></header>
    <main id="inicio">
      <section class="hero"><div class="hero-copy"><p class="eyebrow"><span></span> Diocese de Guaxupé</p><h1>Sua comunidade<br><em>mais perto de você.</em></h1><p class="hero-description">Encontre horários de missas, atividades e informações das paróquias da diocese em um só lugar.</p><div class="hero-trust"><b>✓</b> Horários atualizados pelas próprias paróquias</div></div><div class="hero-art" aria-hidden="true"><i class="sun"></i><i class="cross">✦</i><i class="hill"></i><i class="chapel">✝</i></div></section>
      <section id="missas" class="finder"><div class="finder-heading"><p class="eyebrow dark"><span></span> Encontre uma celebração</p><h2>Onde você quer celebrar?</h2></div><form class="search-panel" (ngSubmit)="load()"><label><span>⌖</span><input [(ngModel)]="city" name="city" placeholder="Em qual cidade?"></label><label><span>⌕</span><input [(ngModel)]="query" name="query" placeholder="Paróquia ou bairro"></label><label><span>◫</span><select [(ngModel)]="sector" name="sector"><option value="">Todos os setores</option><option *ngFor="let item of sectors" [value]="item">{{ item }}</option></select></label><button type="submit">Buscar <b>→</b></button></form><button *ngIf="hasFilters" type="button" class="clear-filters" (click)="clearFilters()">Limpar filtros</button></section>
      <section class="quick-links"><a href="#paroquias"><span class="quick-icon">⌂</span><span><b>Paróquias</b><small>Encontre a sua comunidade</small></span><i>→</i></a><a href="#paroquias"><span class="quick-icon">□</span><span><b>Próximas atividades</b><small>Participe da vida da Igreja</small></span><i>→</i></a><a href="#sobre"><span class="quick-icon">♡</span><span><b>Precisa de ajuda?</b><small>Fale com uma paróquia</small></span><i>→</i></a></section>
      <section id="paroquias" class="parishes"><div class="section-heading"><div><p class="eyebrow dark"><span></span> Comunidades</p><h2>Paróquias para você</h2><p>{{ resultDescription }}</p></div><div class="result-count" *ngIf="!loading"><strong>{{ parishes.length }}</strong> encontradas</div></div><div *ngIf="loading" class="state-message"><span class="spinner"></span> Buscando paróquias...</div><div *ngIf="error" class="state-message error"><b>Não foi possível carregar.</b> {{ error }} <button (click)="load()">Tentar novamente</button></div><div *ngIf="!loading && !error && parishes.length === 0" class="empty-state"><span>⌕</span><h3>Nenhuma paróquia encontrada</h3><p>Experimente buscar por outra cidade ou limpe os filtros.</p><button (click)="clearFilters()">Ver todas as paróquias</button></div><div class="parish-grid" *ngIf="!loading && parishes.length"><article class="parish-card" *ngFor="let parish of parishes; trackBy: trackById"><div class="card-top"><span class="sector-tag">{{ shortSector(parish.sector) }}</span><span class="premium" *ngIf="parish.isPremium">Comunidade parceira</span></div><h3>{{ parish.name }}</h3><p class="location">⌖ {{ parish.city }}, {{ parish.state }}</p><div class="next-mass" *ngIf="parish.massSchedules.length; else noMasses"><span class="mass-icon">✦</span><div><small>MISSAS</small><p><b>{{ dayLabel(parish.massSchedules[0].day) }}</b> · {{ parish.massSchedules[0].time }}</p><em *ngIf="parish.massSchedules[0].description">{{ parish.massSchedules[0].description }}</em></div></div><ng-template #noMasses><div class="next-mass"><span class="mass-icon">–</span><div><small>MISSAS</small><p>Horários em atualização</p></div></div></ng-template><div class="activities" *ngIf="parish.activities.length"><span>Próxima atividade</span><b>{{ parish.activities[0].title }}</b></div><a class="card-link" [href]="parish.phone ? 'tel:' + parish.phone : '#paroquias'">{{ parish.phone ? 'Falar com a paróquia' : 'Ver informações' }} <span>→</span></a></article></div></section>
      <section id="sobre" class="about-band"><div><p class="eyebrow"><span></span> Igreja Conecta</p><h2>Feito para aproximar pessoas e comunidades.</h2></div><p>Esta é uma demonstração com dados de teste. Confirme os horários diretamente com a paróquia antes de se deslocar.</p></section>
    </main><footer><span>© {{ currentYear }} Igreja Conecta</span><span>Um projeto em teste para a Diocese de Guaxupé</span></footer></ng-container>
  `, styles: [`.admin-page{min-height:100vh;background:#f4f6f2;padding-bottom:60px}.admin-header{background:#163d38;color:#fff;padding:24px 8%;display:flex;align-items:center;gap:36px}.admin-header a{font-size:13px;color:#d7e4d8}.admin-header small{letter-spacing:.14em;color:#cfaa5b;font-size:10px}.admin-header h1{margin:5px 0 0;font:700 30px 'Playfair Display',serif}.admin-login,.admin-form-wrap{width:min(760px,calc(100% - 32px));margin:42px auto;background:#fff;border:1px solid #dfe7df;border-radius:8px;padding:32px}.admin-login{max-width:480px}.admin-login h2,.admin-form-wrap h2{margin:0;font:700 28px 'Playfair Display',serif}.admin-login p,.admin-help{color:#728077;line-height:1.5}.admin-login input{width:100%;height:46px;border:1px solid #ccd8cd;border-radius:4px;padding:0 12px;margin:10px 0}.admin-login button,.save-button{height:46px;border:0;border-radius:4px;background:#c9912e;color:#fff;font-weight:700;padding:0 20px;cursor:pointer}.admin-form{display:grid;gap:16px;margin-top:25px}.admin-form label{display:grid;gap:6px;color:#52645b;font-size:13px;font-weight:700}.admin-form input,.admin-form select{height:43px;border:1px solid #ccd8cd;border-radius:4px;padding:0 11px;background:#fff;color:#173d3d;font-size:14px}.form-row{display:grid;grid-template-columns:2fr 1fr;gap:14px}.form-row.three{grid-template-columns:1fr 1fr 2fr}.admin-form fieldset{border:1px solid #dce5dc;border-radius:5px;padding:15px}.admin-form legend{padding:0 6px;font-size:13px;font-weight:700;color:#52645b}.check-row{display:flex!important;align-items:center;gap:8px}.check-row input{height:auto!important;width:auto}.save-button{justify-self:start}.admin-message{color:#277055;font-size:13px;font-weight:700}.admin-error{color:#b34436}@media(max-width:580px){.admin-header{padding:20px;display:block}.admin-header a{display:block;margin-bottom:22px}.admin-login,.admin-form-wrap{padding:24px}.form-row,.form-row.three{grid-template-columns:1fr}}`]
})
export class AppComponent implements OnInit {
  readonly isAdmin = window.location.pathname.replace(/\/+$/, '') === '/admin';
  city = ''; sector = ''; query = ''; parishes: Parish[] = []; loading = false; error = '';
  readonly currentYear = new Date().getFullYear(); readonly sectors = ['Setor Guaxupé', 'Setor Poços de Caldas', 'Setor Passos', 'Setor Cássia'];
  constructor(private readonly parishService: ParishService) {}
  get hasFilters() { return Boolean(this.city || this.sector || this.query); }
  get resultDescription() { return this.hasFilters ? 'Resultados para sua busca na Diocese de Guaxupé.' : 'Conheça as comunidades disponíveis na Diocese de Guaxupé.'; }
  ngOnInit() { this.load(); }
  load() { this.loading = true; this.error = ''; this.parishService.search(this.city, this.sector, this.query).subscribe({ next: data => { this.parishes = data; this.loading = false; }, error: () => { this.error = 'Verifique sua conexão e tente novamente.'; this.loading = false; } }); }
  clearFilters() { this.city = ''; this.sector = ''; this.query = ''; this.load(); }
  trackById(_: number, parish: Parish) { return parish.id; }
  shortSector(sector: string) { return sector.replace('Setor ', ''); }
  dayLabel(day: string) { return ({ Sunday: 'Domingo', Monday: 'Segunda-feira', Tuesday: 'Terça-feira', Wednesday: 'Quarta-feira', Thursday: 'Quinta-feira', Friday: 'Sexta-feira', Saturday: 'Sábado' } as Record<string, string>)[day] ?? day; }
}
