import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { Parish, MassSchedule } from './core/models/parish';
import { ParishService } from './core/services/parish.service';
import { AdminService, MassForm, ParishForm } from './core/services/admin.service';

const days = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'];
const dayNames: Record<string, string> = {
  Monday: 'Segunda-feira', Tuesday: 'Terça-feira', Wednesday: 'Quarta-feira',
  Thursday: 'Quinta-feira', Friday: 'Sexta-feira', Saturday: 'Sábado', Sunday: 'Domingo'
};

function blankParish(): ParishForm {
  return { name: '', sector: '', city: '', state: 'MG', address: '', phone: '', imageUrl: '', isPremium: false,
    massSchedules: [{ day: 'Sunday', time: '', description: '' }] };
}

@Component({
  selector: 'app-admin', standalone: true, imports: [CommonModule, FormsModule],
  styles: [`
    :host{display:block;min-height:100vh;background:#f5f6f3;color:#26362f;font-family:Arial,sans-serif}.admin-header{background:#174c3c;color:#fff;padding:25px 5%;display:flex;align-items:center;justify-content:space-between}.admin-header a{color:#fff;text-decoration:none}.brand{font-family:Georgia,serif;font-size:25px}.admin-main{max-width:1160px;margin:0 auto;padding:38px 22px 70px}.intro{margin-bottom:24px}.intro h1{font-family:Georgia,serif;margin:0 0 8px;color:#174c3c}.intro p{margin:0;color:#69746f}.access{max-width:460px;margin:70px auto;background:#fff;padding:34px;border-radius:16px;box-shadow:0 12px 35px #1b3b3020}.access h1{font-family:Georgia,serif;color:#174c3c}.access input{width:100%;box-sizing:border-box;margin:12px 0 17px}.admin-grid{display:grid;grid-template-columns:1.1fr .9fr;gap:24px;align-items:start}.panel{background:#fff;border:1px solid #e2e7e1;border-radius:16px;padding:25px;box-shadow:0 8px 26px #203a3010}.panel h2{margin:0 0 20px;color:#174c3c;font-family:Georgia,serif}.field-grid{display:grid;grid-template-columns:1fr 1fr;gap:14px}.wide{grid-column:1/-1}label{display:block;font-size:13px;font-weight:bold;color:#3f5149}input,select,textarea{border:1px solid #ccd7d0;border-radius:8px;padding:11px;margin-top:6px;font:inherit;color:#26362f;background:#fff}input,select{width:100%;box-sizing:border-box}textarea{width:100%;box-sizing:border-box;resize:vertical}.premium{display:flex;align-items:center;gap:8px;margin:18px 0}.premium input{width:auto;margin:0}.schedule{display:grid;grid-template-columns:1.1fr .7fr 1fr auto;gap:8px;align-items:end;margin:10px 0;padding:12px;background:#f4f7f4;border-radius:10px}.schedule label{min-width:0}.schedule input,.schedule select{margin-top:5px}.remove{border:0;background:#fbe7e3;color:#a23721;border-radius:8px;padding:10px;cursor:pointer}.link-button{border:0;background:transparent;color:#16634c;font-weight:bold;padding:8px 0;cursor:pointer}.primary{border:0;border-radius:9px;background:#d9a441;color:#22332b;padding:12px 18px;font-weight:bold;cursor:pointer}.actions{display:flex;gap:10px;align-items:center;margin-top:19px}.cancel{border:0;background:transparent;color:#596861;padding:10px;cursor:pointer}.status{font-size:14px;margin:14px 0}.status.error{color:#a23721}.status.ok{color:#197047}.preview{width:100%;height:130px;object-fit:cover;border-radius:9px;margin-top:8px}.parish-list{display:grid;gap:12px}.parish-item{border:1px solid #e1e8e2;border-radius:12px;padding:15px}.parish-item h3{font-size:16px;margin:0 0 5px;color:#174c3c}.parish-item p{margin:0 0 12px;color:#68756e;font-size:14px}.item-actions{display:flex;gap:12px}.edit{color:#16634c}.delete{color:#a23721}@media(max-width:850px){.admin-grid{grid-template-columns:1fr}.field-grid{grid-template-columns:1fr}.schedule{grid-template-columns:1fr 1fr}.schedule label:last-of-type{grid-column:1/-1}.remove{grid-column:2}.admin-header{padding:20px}.admin-main{padding:28px 15px}}`],
  template: `
    <header class="admin-header"><a class="brand" href="/">Igreja Conecta</a><a href="/">← Ver portal público</a></header>
    <section class="access" *ngIf="!unlocked"><h1>Área administrativa</h1><p>Informe a chave para administrar as paróquias.</p><input [(ngModel)]="key" type="password" placeholder="Chave de acesso" (keyup.enter)="unlock()"><button class="primary" (click)="unlock()">Entrar</button><p class="status error" *ngIf="message">{{message}}</p></section>
    <main class="admin-main" *ngIf="unlocked"><div class="intro"><h1>Gestão de paróquias</h1><p>Cadastre informações, foto e todos os horários de missa de cada igreja.</p></div><p class="status" [class.error]="isError" [class.ok]="!isError" *ngIf="message">{{message}}</p>
      <div class="admin-grid"><section class="panel"><h2>{{editing ? 'Editar paróquia' : 'Nova paróquia'}}</h2><div class="field-grid">
        <label>Nome da paróquia<input [(ngModel)]="form.name" placeholder="Ex.: Paróquia Nossa Senhora..." /></label><label>Setor<input [(ngModel)]="form.sector" placeholder="Ex.: Guaxupé" /></label>
        <label>Cidade<input [(ngModel)]="form.city" /></label><label>UF<input [(ngModel)]="form.state" maxlength="2" /></label>
        <label class="wide">Endereço<input [(ngModel)]="form.address" /></label><label>Telefone<input [(ngModel)]="form.phone" /></label>
        <label>Link da foto<input [(ngModel)]="form.imageUrl" type="url" placeholder="https://..." /></label>
        <img class="preview" *ngIf="form.imageUrl" [src]="form.imageUrl" alt="Prévia da paróquia" (error)="imageFailed = true" [style.display]="imageFailed ? 'none' : 'block'">
      </div><label class="premium"><input [(ngModel)]="form.isPremium" type="checkbox" /> Página completa da paróquia</label>
      <h2>Horários de missa</h2><p>Inclua quantos horários forem necessários, inclusive no mesmo dia.</p>
      <div class="schedule" *ngFor="let mass of form.massSchedules; let i = index"><label>Dia<select [(ngModel)]="mass.day"><option *ngFor="let day of days" [value]="day">{{dayName(day)}}</option></select></label><label>Horário<input [(ngModel)]="mass.time" placeholder="07h" /></label><label>Observação<input [(ngModel)]="mass.description" placeholder="Ex.: Matriz" /></label><button class="remove" type="button" (click)="removeMass(i)" [disabled]="form.massSchedules.length === 1">Remover</button></div>
      <button class="link-button" type="button" (click)="addMass()">+ Adicionar outro horário</button><div class="actions"><button class="primary" (click)="save()">{{editing ? 'Salvar alterações' : 'Cadastrar paróquia'}}</button><button class="cancel" *ngIf="editing" (click)="reset()">Cancelar edição</button></div></section>
      <section class="panel"><h2>Paróquias cadastradas</h2><p *ngIf="loading">Carregando...</p><p *ngIf="!loading && !items.length">Nenhuma paróquia cadastrada ainda.</p><div class="parish-list"><article class="parish-item" *ngFor="let parish of items"><h3>{{parish.name}}</h3><p>{{parish.city}} · {{parish.sector}} · {{parish.massSchedules.length}} horário(s)</p><div class="item-actions"><button class="link-button edit" (click)="edit(parish)">Editar</button><button class="link-button delete" (click)="remove(parish)">Excluir</button></div></article></div></section>
      </div></main>`
})
export class AdminComponent {
  readonly days = days; key = sessionStorage.getItem('igrejaConectaAdminKey') || ''; unlocked = false; loading = false; editing = false; imageFailed = false; isError = false; message = ''; items: ParishForm[] = []; form = blankParish();
  constructor(private readonly admin: AdminService) {}
  dayName(day: string): string { return dayNames[day] || day; }
  unlock(): void { this.message = ''; this.loading = true; this.admin.list(this.key).subscribe({ next: items => { sessionStorage.setItem('igrejaConectaAdminKey', this.key); this.unlocked = true; this.items = items; this.loading = false; }, error: () => { this.loading = false; this.isError = true; this.message = 'Chave inválida ou serviço indisponível.'; } }); }
  load(): void { this.loading = true; this.admin.list(this.key).subscribe({ next: items => { this.items = items; this.loading = false; }, error: () => { this.loading = false; this.isError = true; this.message = 'Não foi possível carregar as paróquias.'; } }); }
  addMass(): void { this.form.massSchedules.push({ day: 'Sunday', time: '', description: '' }); }
  removeMass(index: number): void { if (this.form.massSchedules.length > 1) this.form.massSchedules.splice(index, 1); }
  edit(parish: ParishForm): void { this.editing = true; this.imageFailed = false; this.form = { ...parish, massSchedules: parish.massSchedules.map(m => ({ ...m })) }; window.scrollTo({ top: 0, behavior: 'smooth' }); }
  reset(): void { this.editing = false; this.imageFailed = false; this.form = blankParish(); }
  save(): void { this.message = ''; this.isError = false; const success = () => { this.message = this.editing ? 'Paróquia atualizada com sucesso.' : 'Paróquia cadastrada com sucesso.'; this.reset(); this.load(); }; const failure = (error: any) => { this.isError = true; this.message = error?.error?.message || 'Não foi possível salvar a paróquia.'; }; if (this.editing) this.admin.update(this.key, this.form).subscribe({ next: success, error: failure }); else this.admin.create(this.key, this.form).subscribe({ next: success, error: failure }); }
  remove(parish: ParishForm): void { if (!parish.id || !confirm(`Excluir ${parish.name}?`)) return; this.admin.delete(this.key, parish.id).subscribe({ next: () => { this.message = 'Paróquia excluída com sucesso.'; this.isError = false; if (this.form.id === parish.id) this.reset(); this.load(); }, error: () => { this.isError = true; this.message = 'Não foi possível excluir a paróquia.'; } }); }
}

@Component({
  selector: 'app-root', standalone: true, imports: [CommonModule, FormsModule, AdminComponent],
  styles: [`
    :host{display:block;color:#243830;font-family:Arial,sans-serif}.home{background:#fbfcf9;min-height:100vh}.hero{background:linear-gradient(125deg,#123f32,#1e6851);padding:26px 6% 80px;color:#fff}.nav{display:flex;justify-content:space-between;align-items:center}.logo{font:26px Georgia,serif}.nav a{color:#fff;text-decoration:none;border:1px solid #ffffff80;border-radius:20px;padding:8px 13px}.hero-content{max-width:820px;margin:72px auto 0;text-align:center}.hero h1{font:clamp(32px,5vw,56px) Georgia,serif;margin:0 0 15px}.hero p{font-size:18px;line-height:1.55;color:#e4efe9}.search{max-width:1060px;margin:-31px auto 0;padding:0 20px}.search-box{background:#fff;border-radius:15px;padding:16px;box-shadow:0 10px 30px #113a2c22;display:grid;grid-template-columns:1fr 1fr 1fr auto;gap:10px}.search input,.search select{border:1px solid #d6dfd8;border-radius:8px;padding:12px;font:inherit}.search button{background:#d6a13f;border:0;border-radius:8px;padding:0 19px;font-weight:bold;cursor:pointer}.content{max-width:1120px;margin:0 auto;padding:46px 20px 70px}.section-title{display:flex;justify-content:space-between;align-items:end;margin-bottom:20px}.section-title h2{font:32px Georgia,serif;color:#174c3c;margin:0}.section-title p{color:#68766f}.cards{display:grid;grid-template-columns:repeat(3,1fr);gap:20px}.card{background:#fff;border:1px solid #e0e7e1;border-radius:15px;overflow:hidden;box-shadow:0 8px 22px #1d3a3010}.photo{height:170px;background:#e4eee8;display:grid;place-items:center;overflow:hidden}.photo img{width:100%;height:100%;object-fit:cover}.placeholder{font:44px Georgia,serif;color:#356452}.card-body{padding:19px}.eyebrow{font-size:12px;text-transform:uppercase;letter-spacing:.08em;color:#a77722;font-weight:bold}.card h3{font:22px Georgia,serif;color:#174c3c;margin:7px 0}.address{font-size:14px;color:#65736b;min-height:36px}.schedule-box{margin-top:16px;padding-top:13px;border-top:1px solid #e7ece7}.schedule-title{font-size:13px;font-weight:bold;color:#174c3c;margin-bottom:7px}.day-row{font-size:14px;display:flex;gap:8px;padding:4px 0}.day-row strong{min-width:86px;color:#385047}.empty{text-align:center;padding:48px;color:#68766f}@media(max-width:820px){.search-box{grid-template-columns:1fr}.search button{padding:12px}.cards{grid-template-columns:1fr}.hero{padding-bottom:62px}.hero-content{margin-top:50px}.section-title{display:block}}`],
  template: `<app-admin *ngIf="isAdmin"></app-admin><main class="home" *ngIf="!isAdmin"><section class="hero"><nav class="nav"><span class="logo">Igreja Conecta</span><a href="/admin">Área da paróquia</a></nav><div class="hero-content"><h1>Encontre uma igreja perto de você</h1><p>Horários de missa e informações das paróquias da Diocese de Guaxupé em um só lugar.</p></div></section><section class="search"><div class="search-box"><input [(ngModel)]="query" (keyup.enter)="search()" placeholder="Nome da paróquia ou cidade" /><input [(ngModel)]="city" (keyup.enter)="search()" placeholder="Cidade" /><input [(ngModel)]="sector" (keyup.enter)="search()" placeholder="Setor" /><button (click)="search()">Buscar</button></div></section><section class="content"><div class="section-title"><div><h2>Paróquias e horários</h2><p>Planeje sua participação nas celebrações.</p></div><p *ngIf="loading">Buscando...</p></div><div class="cards" *ngIf="!loading && parishes.length"><article class="card" *ngFor="let parish of parishes"><div class="photo"><img *ngIf="parish.imageUrl" [src]="parish.imageUrl" [alt]="parish.name" /><span class="placeholder" *ngIf="!parish.imageUrl">✦</span></div><div class="card-body"><span class="eyebrow">{{parish.city}} · {{parish.sector}}</span><h3>{{parish.name}}</h3><p class="address">{{parish.address || 'Endereço em atualização'}}</p><div class="schedule-box"><div class="schedule-title">Horários de missa</div><div class="day-row" *ngFor="let group of groupedSchedules(parish.massSchedules)"><strong>{{dayName(group.day)}}</strong><span>{{group.times.join(', ')}}</span></div><p *ngIf="!parish.massSchedules.length">Horários em atualização</p></div></div></article></div><div class="empty" *ngIf="!loading && !parishes.length">Nenhuma paróquia encontrada. Ajuste sua busca e tente novamente.</div></section></main>`
})
export class AppComponent implements OnInit {
  isAdmin = window.location.pathname.replace(/\/+$/, '') === '/admin'; parishes: Parish[] = []; city = ''; sector = ''; query = ''; loading = false;
  constructor(private readonly parishService: ParishService) {}
  ngOnInit(): void { if (!this.isAdmin) this.search(); }
  search(): void { this.loading = true; this.parishService.search(this.city, this.sector, this.query).subscribe({ next: value => { this.parishes = value; this.loading = false; }, error: () => { this.parishes = []; this.loading = false; } }); }
  dayName(day: string): string { return dayNames[day] || day; }
  groupedSchedules(schedules: MassSchedule[]): { day: string; times: string[] }[] { return days.map(day => ({ day, times: schedules.filter(x => x.day === day).map(x => x.time) })).filter(x => x.times.length); }
}
