import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Parish, MassSchedule } from './core/models/parish';
import { ParishService } from './core/services/parish.service';

@Component({
  selector: 'app-root', standalone: true, imports: [CommonModule],
  styles: [`:host{display:block;min-height:100vh;background:#f8f8f4;color:#173d3d;font-family:Arial,sans-serif}.top{background:#0b4039;color:#fff;padding:24px 8%}.top a{color:#fff;text-decoration:none}.top h1{font:34px Georgia,serif;margin:22px 0 4px}.content{max-width:1080px;margin:36px auto;padding:0 22px}.hero{display:grid;grid-template-columns:260px 1fr;gap:28px;background:#fff;border-radius:15px;overflow:hidden;box-shadow:0 8px 24px #173d3d16}.hero img,.fallback{width:100%;height:230px;object-fit:cover;background:#dce9df}.fallback{display:grid;place-items:center;font-size:48px}.hero-copy{padding:22px}.hero-copy h2{font:30px Georgia,serif;margin:4px 0 15px}.meta{color:#687b71}.section{margin-top:34px}.section h2{font:28px Georgia,serif}.communities{display:grid;grid-template-columns:repeat(auto-fit,minmax(270px,1fr));gap:18px}.community{background:#fff;border:1px solid #e1e8e1;border-radius:12px;overflow:hidden}.community img{width:100%;height:150px;object-fit:cover}.community-body{padding:18px}.community h3{font:22px Georgia,serif;margin:0 0 9px}.mass{display:flex;gap:8px;margin:7px 0;font-size:14px}.mass b{min-width:90px;color:#32614f}.empty{padding:35px;text-align:center}@media(max-width:650px){.hero{grid-template-columns:1fr}.hero img,.fallback{height:190px}}`],
  template: `<header class="top"><a href="/">← Voltar ao portal</a><h1 *ngIf="parish">{{parish.name}}</h1></header><main class="content" *ngIf="parish; else loading"><section class="hero"><img *ngIf="parish.imageUrl" [src]="parish.imageUrl" [alt]="parish.name"><div class="fallback" *ngIf="!parish.imageUrl">✦</div><div class="hero-copy"><span>{{parish.city}} · {{parish.sector}}</span><h2>Matriz</h2><p class="meta">{{parish.address}}</p><p class="meta" *ngIf="parish.phone">{{parish.phone}}</p><div class="mass" *ngFor="let item of grouped(parish.massSchedules)"><b>{{day(item.day)}}</b><span>{{item.times.join(' – ')}}</span></div></div></section><section class="section"><h2>Comunidades</h2><div class="communities" *ngIf="parish.communities.length; else none"><article class="community" *ngFor="let community of parish.communities"><img *ngIf="community.imageUrl" [src]="community.imageUrl" [alt]="community.name"><div class="community-body"><h3>{{community.name}}</h3><p class="meta">{{community.address}}</p><p class="meta" *ngIf="community.phone">{{community.phone}}</p><div class="mass" *ngFor="let item of grouped(community.massSchedules)"><b>{{day(item.day)}}</b><span>{{item.times.join(' – ')}}</span></div></div></article></div><ng-template #none><div class="empty">Esta paróquia ainda não possui comunidades cadastradas.</div></ng-template></section></main><ng-template #loading><p class="empty" *ngIf="loading">Carregando informações da paróquia...</p><p class="empty" *ngIf="!loading">Esta página é exclusiva para paróquias PLUS. Consulte os horários pelo portal.</p></ng-template>`
})
export class ParishDetailsComponent implements OnInit {
  parish?: Parish; loading = true; private readonly id = location.pathname.split('/').pop() || ''; readonly order = ['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'];
  constructor(private readonly service: ParishService) {}
  ngOnInit(): void { this.service.getById(this.id).subscribe({ next: value => { this.parish = value; this.loading = false; }, error: () => this.loading = false }); }
  day(value: string): string { return ({ Monday:'Segunda',Tuesday:'Terça',Wednesday:'Quarta',Thursday:'Quinta',Friday:'Sexta',Saturday:'Sábado',Sunday:'Domingo' } as Record<string,string>)[value] || value; }
  grouped(items: MassSchedule[]): { day: string; times: string[] }[] { return this.order.map(day => ({ day, times: [...new Set(items.filter(x => x.day === day).map(x => String(x.time || 'Horário a confirmar')))] })).filter(x => x.times.length); }
}
