import { bootstrapApplication } from '@angular/platform-browser';
import { provideHttpClient } from '@angular/common/http';
import { AppComponent } from './app/app.component';
import { ParishDetailsComponent } from './app/parish-details.component';
import { AdminPageComponent } from './app/admin-page.component';
const path = location.pathname.replace(/\/+$/, '') || '/';
const options = { providers: [provideHttpClient()] };
if (path === '/admin') bootstrapApplication(AdminPageComponent, options).catch(console.error);
else if (path.startsWith('/paroquias/')) bootstrapApplication(ParishDetailsComponent, options).catch(console.error);
else bootstrapApplication(AppComponent, options).catch(console.error);
